# Site settings
author: CPHblogger
title: So You Want to Learn to Code
header-img: img/home-bg.png
email: cp.halpenny@gmail.com
copyright_name: CPHblogger
description: > # this means to ignore newlines until "baseurl:"
  Coding bootcamps are popping up all over. So whatâ€™s it like to attend?
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  chalpenny

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
